
services:
  flagd:
    image: ghcr.io/open-feature/flagd:latest
    volumes:
      - ./flags:/flags
    command: [
      'start',
      '--uri',
      'file:./flags/demo.flagd.json',
    ]
    ports:
      - "8013:8013"
      - "8015:8015"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
    depends_on:
      - flagd

